# Generated by Django 3.2.8 on 2021-10-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='emails',
            new_name='email',
        ),
    ]
